### ISSUE TITLE
Broken function calls

### ISSUE THREAD

**Issue by noahdasanaike** [dickoa/rgeoboundaries#19]
Seems like the function call geoboundaries() and its derivative functions (like gb_adm0()) are all broken; if I don't specify a country (e.g., rgeoboundaries::geoboundaries(adm_lvl = "adm0") or rgeoboundaries::gb_adm0()), I get "argument "canNames" is missing, with no default"; if I do specify a country (e.g., rgeoboundaries::geoboundaries("Japan", adm_lvl = "adm0")), I get "unused argument (country)". This is under the newest development release.

**Comment by fang19911030** [comment]
Yes, I have the same issue.

**Comment by DanRunfola** [comment]
@rohith4444 flagging this for Rohith - will see if we can get this resolved today.

Could you provide a quick example of expected behavior, so we can use it for testing?

(Many apologies - we're a python crew here, so learning-by-doing in the R landscape.  Once we get these issues resolved this package should be stable "forever", as our API almost never changes! )

Dan

**Comment by rohith4444** [comment]
@DanRunfola @fang19911030 @noahdasanaike 

Hello everyone, I've addressed the recent bugs. The issue arose from a recent update where we introduced a new column called 'boundaryCanonical' in the output dataframe. I hadn't accounted for how to handle cases where there might be NULL values. As of now, 'boundaryCanonical' will only appear when a country is specified. I believe I've resolved all the bugs, but please do let me know if you come across any others."

**Comment by DanRunfola** [comment]
Fixed with https://github.com/wmgeolab/rgeoboundaries/commit/fbdb45e6f34cdd608e1f4c2bea048e7cebce5dcb - please let us know if you still run into issues after updating.

Best,
Dan
